name: chat-server
version: 0.1.0.0
github: "Disco-Dave/chat-server"
license: BSD3
author: "David Burkett"
maintainer: "david@davidburkett.xyz"
copyright: "2021 David Burkett"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Disco-Dave/chat-server#readme>

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fwrite-ide-info
  - -hiedir=.hie

default-extensions:
  - DeriveGeneric
  - DerivingVia
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedStrings
  - RecordWildCards
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - containers
  - envparse
  - katip
  - load-env
  - mtl
  - stm
  - text
  - time
  - unliftio
  - uuid
  - websockets

library:
  source-dirs: src

executables:
  chat-server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - chat-server

tests:
  chat-server-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - chat-server
      - aeson-qq
      - directory
      - hspec
      - port-utils
      - silently
